In [1]:
import os
import pandas as pd

In [2]:
os.chdir("/Users/mennatullahalsoudi/Downloads")

In [3]:
os.getcwd

In [4]:
df=pd.read_csv("Profile (1).csv")

In [5]:
df.head(10)

,Unnamed: 0,Unnamed: 0.1,User ID,Interests,Age
0,1,1,95258c36-5b6b-4591-85ee-0c43f503c1d5,['tennis'],23
1,2,2,a8229d24-f219-4930-a382-24049a8f73bb,"['fitness', 'cooking', 'animals', 'travel']",25
2,4,4,3af8d78b-55c4-4ac0-8161-7cc3f6ec11c9,['education'],44
3,5,5,2bd9c167-e06c-47c1-a978-3403d6724606,"['culture', 'healthy eating']",28
4,8,8,22056f9e-4654-44e9-930d-2fabdeb80f95,"['public speaking', 'science', 'veganism', 'te...",23
5,9,9,30a7de62-d6a1-47d6-963f-0724adf18c4b,['animals'],30
6,10,10,c7b6e374-1bef-48c3-8222-cc231dbd5cce,"['veganism', 'science', 'education']",8
7,11,11,eff1e86a-8ede-4a41-818b-9442e3181ee3,"['studying', 'fitness']",25
8,12,12,346174b1-4661-4cdd-8c47-66dbd013cd56,"['travel', 'veganism', 'food']",32
9,13,13,0f1f6aef-b094-4b4d-b6b6-412ebc42c12b,"['healthy eating', 'public speaking', 'soccer']",34

In [6]:
df.isna()

     Unnamed: 0  Unnamed: 0.1  User ID  Interests    Age
0         False         False    False      False  False
1         False         False    False      False  False
2         False         False    False      False  False
3         False         False    False      False  False
4         False         False    False      False  False
..          ...           ...      ...        ...    ...
420       False         False    False      False  False
421       False         False    False      False  False
422       False         False    False      False  False
423       False         False    False      False  False
424       False         False    False      False  False

[425 rows x 5 columns]

In [7]:
#Making sure there is no none values
df.dropna()

,Unnamed: 0,Unnamed: 0.1,User ID,Interests,Age
0,1,1,95258c36-5b6b-4591-85ee-0c43f503c1d5,['tennis'],23
1,2,2,a8229d24-f219-4930-a382-24049a8f73bb,"['fitness', 'cooking', 'animals', 'travel']",25
2,4,4,3af8d78b-55c4-4ac0-8161-7cc3f6ec11c9,['education'],44
3,5,5,2bd9c167-e06c-47c1-a978-3403d6724606,"['culture', 'healthy eating']",28
4,8,8,22056f9e-4654-44e9-930d-2fabdeb80f95,"['public speaking', 'science', 'veganism', 'te...",23
...,...,...,...,...,...
420,494,494,7246fed1-8725-4dbb-bccd-5451346f122d,"['food', 'healthy eating']",19
421,495,495,1f7e22c8-558a-4b6f-a04f-b219593f029e,"['tennis', 'veganism', 'education', 'soccer']",21
422,497,497,db0066e1-83cc-43f3-990b-983010aa5370,['soccer'],14
423,498,498,d6204684-926d-41db-ae9c-a7bf2e76313a,"['public speaking', 'dogs']",24
424,499,499,07f4dcd0-2bf3-4f21-9da3-b054b511ae00,"['education', 'science', 'animals', 'public sp...",24

In [8]:
df.isna().sum()

Unnamed: 0      0
Unnamed: 0.1    0
User ID         0
Interests       0
Age             0
dtype: int64

In [9]:
#Making sure all the values are numerical
df["Age"].mean()

25.305882352941175

In [10]:
df["Age"].unique()

array([23, 25, 44, 28, 30,  8, 32, 34, 42, 19, 21, 14, 41, 29, 39, 38,  7,
        9, 16, 40, 35, 36, 26, 33, 20, 11, 18, 10, 15, 17,  6, 43, 22, 27,
       24, 31, 37, 13, 12])

In [11]:
df.head(10)

,Unnamed: 0,Unnamed: 0.1,User ID,Interests,Age
0,1,1,95258c36-5b6b-4591-85ee-0c43f503c1d5,['tennis'],23
1,2,2,a8229d24-f219-4930-a382-24049a8f73bb,"['fitness', 'cooking', 'animals', 'travel']",25
2,4,4,3af8d78b-55c4-4ac0-8161-7cc3f6ec11c9,['education'],44
3,5,5,2bd9c167-e06c-47c1-a978-3403d6724606,"['culture', 'healthy eating']",28
4,8,8,22056f9e-4654-44e9-930d-2fabdeb80f95,"['public speaking', 'science', 'veganism', 'te...",23
5,9,9,30a7de62-d6a1-47d6-963f-0724adf18c4b,['animals'],30
6,10,10,c7b6e374-1bef-48c3-8222-cc231dbd5cce,"['veganism', 'science', 'education']",8
7,11,11,eff1e86a-8ede-4a41-818b-9442e3181ee3,"['studying', 'fitness']",25
8,12,12,346174b1-4661-4cdd-8c47-66dbd013cd56,"['travel', 'veganism', 'food']",32
9,13,13,0f1f6aef-b094-4b4d-b6b6-412ebc42c12b,"['healthy eating', 'public speaking', 'soccer']",34

In [12]:
df.drop("Age",axis=1)

,Unnamed: 0,Unnamed: 0.1,User ID,Interests
0,1,1,95258c36-5b6b-4591-85ee-0c43f503c1d5,['tennis']
1,2,2,a8229d24-f219-4930-a382-24049a8f73bb,"['fitness', 'cooking', 'animals', 'travel']"
2,4,4,3af8d78b-55c4-4ac0-8161-7cc3f6ec11c9,['education']
3,5,5,2bd9c167-e06c-47c1-a978-3403d6724606,"['culture', 'healthy eating']"
4,8,8,22056f9e-4654-44e9-930d-2fabdeb80f95,"['public speaking', 'science', 'veganism', 'te..."
...,...,...,...,...
420,494,494,7246fed1-8725-4dbb-bccd-5451346f122d,"['food', 'healthy eating']"
421,495,495,1f7e22c8-558a-4b6f-a04f-b219593f029e,"['tennis', 'veganism', 'education', 'soccer']"
422,497,497,db0066e1-83cc-43f3-990b-983010aa5370,['soccer']
423,498,498,d6204684-926d-41db-ae9c-a7bf2e76313a,"['public speaking', 'dogs']"
424,499,499,07f4dcd0-2bf3-4f21-9da3-b054b511ae00,"['education', 'science', 'animals', 'public sp..."

In [13]:
df

,Unnamed: 0,Unnamed: 0.1,User ID,Interests,Age
0,1,1,95258c36-5b6b-4591-85ee-0c43f503c1d5,['tennis'],23
1,2,2,a8229d24-f219-4930-a382-24049a8f73bb,"['fitness', 'cooking', 'animals', 'travel']",25
2,4,4,3af8d78b-55c4-4ac0-8161-7cc3f6ec11c9,['education'],44
3,5,5,2bd9c167-e06c-47c1-a978-3403d6724606,"['culture', 'healthy eating']",28
4,8,8,22056f9e-4654-44e9-930d-2fabdeb80f95,"['public speaking', 'science', 'veganism', 'te...",23
...,...,...,...,...,...
420,494,494,7246fed1-8725-4dbb-bccd-5451346f122d,"['food', 'healthy eating']",19
421,495,495,1f7e22c8-558a-4b6f-a04f-b219593f029e,"['tennis', 'veganism', 'education', 'soccer']",21
422,497,497,db0066e1-83cc-43f3-990b-983010aa5370,['soccer'],14
423,498,498,d6204684-926d-41db-ae9c-a7bf2e76313a,"['public speaking', 'dogs']",24
424,499,499,07f4dcd0-2bf3-4f21-9da3-b054b511ae00,"['education', 'science', 'animals', 'public sp...",24

In [14]:
#Getting rid of all the unlogical values
for i in range(len(df)):
    if df["Age"][i]<=5:
        df.drop([i],axis=0,inplace=True)

In [15]:
df.dtypes

Unnamed: 0       int64
Unnamed: 0.1     int64
User ID         object
Interests       object
Age              int64
dtype: object

In [16]:
#Cleaning the intrest columns 
df.iloc[0:50,:]

,Unnamed: 0,Unnamed: 0.1,User ID,Interests,Age
0,1,1,95258c36-5b6b-4591-85ee-0c43f503c1d5,['tennis'],23
1,2,2,a8229d24-f219-4930-a382-24049a8f73bb,"['fitness', 'cooking', 'animals', 'travel']",25
2,4,4,3af8d78b-55c4-4ac0-8161-7cc3f6ec11c9,['education'],44
3,5,5,2bd9c167-e06c-47c1-a978-3403d6724606,"['culture', 'healthy eating']",28
4,8,8,22056f9e-4654-44e9-930d-2fabdeb80f95,"['public speaking', 'science', 'veganism', 'te...",23
5,9,9,30a7de62-d6a1-47d6-963f-0724adf18c4b,['animals'],30
6,10,10,c7b6e374-1bef-48c3-8222-cc231dbd5cce,"['veganism', 'science', 'education']",8
7,11,11,eff1e86a-8ede-4a41-818b-9442e3181ee3,"['studying', 'fitness']",25
8,12,12,346174b1-4661-4cdd-8c47-66dbd013cd56,"['travel', 'veganism', 'food']",32
9,13,13,0f1f6aef-b094-4b4d-b6b6-412ebc42c12b,"['healthy eating', 'public speaking', 'soccer']",34
10,15,15,8665a934-dc22-482b-9289-2e2c9d6a4095,"['healthy eating', 'food', 'soccer', 'healthy ...",42
11,16,16,d4dc38d4-5c80-428f-95da-b746a275531c,"['education', 'culture', 'food']",30
12,17,17,5ff89fb3-b364-494f-b62d-07097b2ffa12,"['food', 'healthy eating', 'culture', 'educati...",19
13,18,18,bbef3be1-172e-44bb-be3b-013140707ecf,"['studying', 'public speaking', 'soccer', 'food']",21
14,19,19,fb4654ff-ce23-4a77-b52a-50f8948b5664,"['culture', 'public speaking']",14
15,20,20,77908afa-eff6-49a9-b042-04fff799a0ff,['tennis'],21
16,21,21,26c6734f-42b6-48f8-a08e-e1c3a79019d0,"['cooking', 'animals']",41
17,22,22,41b0ee09-2868-4c4b-a22d-b533a7fa46af,"['soccer', 'studying', 'science']",29
18,23,23,2ab641a8-6ad4-4d1a-8511-d87ff5346773,"['education', 'technology']",39
19,24,24,da97952a-2eba-46c4-a19e-3df3c40a1524,"['animals', 'travel', 'science', 'studying']",38
20,25,25,92c3576c-8634-42a8-8005-6e1ff8c207e8,['veganism'],25
21,26,26,a1a9c0bd-785a-478f-a19e-9eb48fae0bd6,"['public speaking', 'education', 'culture', 's...",7
22,27,27,e8493c32-7f6f-4e57-a691-cf0df6f015c9,"['soccer', 'animals']",21
23,29,29,dcc6000c-ba92-472c-8bc1-9e9ca30b475b,"['education', 'food']",9
24,30,30,9ce133df-bd87-4559-96d7-a402add824ca,"['science', 'studying', 'culture', 'culture']",16
25,31,31,63e07d14-7bed-44b8-9cf0-4a7e9b2a99ea,"['dogs', 'studying', 'public speaking']",32
26,32,32,a559688e-3f10-436f-a25e-8ad553eacb89,"['studying', 'tennis']",28
27,33,33,3c45659f-e24d-4b0d-8210-0b7704ea1ac6,"['education', 'studying', 'education', 'culture']",14
28,34,34,2aae6657-1214-4119-8cde-6b0dc5cd5529,"['healthy eating', 'dogs', 'science', 'soccer']",40
29,36,36,0c347562-ce55-450b-91ab-0707662b36f5,"['animals', 'culture']",35
30,37,37,b143cd2b-20b1-4e9c-9bb7-cfb359b33d01,['soccer'],36
31,38,38,3f2d07e5-3604-4873-9737-bb44340773d8,['fitness'],26
32,40,40,9e9c6089-692f-406c-afee-50f62c127e9d,"['tennis', 'travel', 'science', 'education']",16
33,41,41,fd7396b2-a18b-449c-b326-e676aebd7776,['veganism'],41
34,42,42,9dcb5fd8-9e7f-40d3-bd1d-edf33ecf6388,"['food', 'animals', 'science', 'soccer']",33
35,43,43,dab237a2-dcc9-4322-a9b6-b2d16ee38c78,"['healthy eating', 'healthy eating']",8
36,44,44,1932a904-86ba-4438-bb52-b7e6516a4019,['dogs'],20
37,46,46,7d624010-a0e7-455b-a606-48c5c467dd80,"['food', 'animals']",23
38,48,48,f9ecf6a2-8402-43b3-bf22-8cd54394ea02,['veganism'],28
39,49,49,132b1407-16fa-48f8-8112-3e426974bbb7,"['healthy eating', 'cooking']",11
40,50,50,b9480379-4b96-412c-8dca-96fff9ae81a3,"['food', 'soccer', 'healthy eating']",21
41,51,51,fe15963d-0a77-4247-9bc6-04e146b826b2,"['food', 'tennis']",38
42,52,52,69527334-c362-47df-87fc-5e2b5e2605e5,"['travel', 'tennis']",38
43,53,53,6e98e5c2-b7d7-4915-bb20-d01a42d29dee,['travel'],18
44,54,54,90e2caab-9daa-4bf0-8104-c25e6c70c59d,"['cooking', 'travel', 'animals']",33
45,55,55,43dc107a-bd3f-4cfe-96f7-8d17ca485bc2,['education'],32
46,56,56,85a3acae-0e71-49f4-a6ee-13d3df1f4962,['public speaking'],9
47,57,57,4cff698b-def1-497c-a78e-75058de67fe8,['animals'],38
48,61,61,ad9f5c2f-aa30-4baf-b084-56b1a4b63b09,"['public speaking', 'technology', 'science']",16
49,62,62,7bf3ce80-784e-42a0-b06a-dbbd1e31a9b7,['dogs'],8

In [17]:
df.iloc[60:100,:]

,Unnamed: 0,Unnamed: 0.1,User ID,Interests,Age
60,75,75,6fd58dea-315a-4ab2-8023-424a6ff455cd,"['food', 'tennis']",28
61,76,76,35d6a1f3-e358-4d4b-8074-05f3b7f35c2a,"['cooking', 'culture', 'studying', 'tennis']",32
62,77,77,e3417115-6e56-4f55-a4ae-70353582a8c4,"['healthy eating', 'public speaking']",6
63,78,78,9d0a0b94-b081-40d7-bf56-6f8f4750dbaf,"['studying', 'science']",16
64,79,79,29ba1f29-2e45-41bd-9c43-05d0dae6c1c6,['technology'],36
65,80,80,0c5b0547-820a-4beb-832e-3162f74ccfa7,['tennis'],17
66,81,81,48e26178-5cdd-4568-9990-d3bc5937910b,"['fitness', 'technology', 'veganism']",43
67,82,82,40e643fb-369c-4ecb-beb7-810114f331fa,"['dogs', 'soccer']",14
68,84,84,0a1cde57-79ab-4c61-b664-1d3b290b43cf,['public speaking'],14
69,85,85,6ecb39b1-8f85-44f1-b2f3-0cffcba4d731,"['animals', 'travel', 'travel']",22
70,86,86,b6d04982-1509-41ab-a700-b390d6cb4d02,"['tennis', 'fitness']",39
71,87,87,d55f3314-96cc-4a5d-b650-f43f094cd3c3,"['tennis', 'healthy eating', 'cooking', 'tennis']",36
72,88,88,7b7b5825-2ae1-4119-99a7-e638f13267a0,"['cooking', 'technology', 'public speaking', '...",15
73,89,89,f182f7d5-e202-4e89-832e-02205dd2ff02,"['cooking', 'technology', 'food']",32
74,90,90,03e3a23a-a77a-41da-9ecd-3f2ff9e5bc90,['dogs'],33
75,91,91,98411adf-cfc0-400d-aac8-e215571ef3f2,"['healthy eating', 'public speaking', 'food']",29
76,92,92,4607d7b0-3313-49b8-9f73-5b8227fc5b67,['cooking'],10
77,93,93,1798905d-6c3a-4e5d-a9d1-ce429b1260d7,['studying'],32
78,94,94,08c64787-e47b-4a7f-b00b-5590eb5fbc3a,"['soccer', 'veganism']",27
79,95,95,2af7f476-41b6-4147-aac7-0bbcb5043895,"['veganism', 'studying']",9
80,96,96,64b33556-9ecf-4ebc-8b4c-f829ab1a4881,"['food', 'animals']",16
81,97,97,e89d4cb0-3bec-43b8-8060-719983fe68a9,['technology'],6
82,98,98,69532ce2-1ffe-4187-8042-0230d115b24e,"['studying', 'healthy eating']",35
83,99,99,427fa55b-7f49-4981-bcd7-59fee8efb512,['science'],27
84,102,102,48bed4d7-0329-472c-96d9-b23a103eb834,"['cooking', 'veganism', 'tennis']",36
85,103,103,ad4bd878-55e7-487c-a4db-470b23bbd832,"['veganism', 'cooking', 'food', 'science']",11
86,104,104,1e571af5-1796-424c-b744-a925897d44a3,"['travel', 'food', 'healthy eating']",15
87,105,105,ae600af5-c1f0-4b1f-adb0-1b4c246373e4,"['soccer', 'fitness', 'healthy eating', 'vegan...",36
88,106,106,2f112802-2501-45b5-a9d9-470cda6ef23e,"['travel', 'food', 'healthy eating']",10
89,107,107,d74e1b39-7b34-4bcb-a24d-e215097187f5,"['science', 'cooking', 'travel']",15
90,108,108,7000ac2e-87a0-4e23-b342-5f150e03f9ef,"['travel', 'veganism', 'healthy eating']",34
91,109,109,b76ebf8d-3f04-4e7f-aec8-22575f68d9e2,"['food', 'culture']",30
92,110,110,80c36ce2-2cef-4a47-a563-d2a60a2b1825,"['culture', 'studying', 'education']",10
93,111,111,bfe23c39-f814-4282-b0f7-506cd8295b8a,['public speaking'],15
94,112,112,a6e32004-8866-40e5-aaeb-e159c13fd42a,"['technology', 'dogs', 'tennis', 'animals']",23
95,113,113,cafa0d07-63be-4b5b-bc7f-c4f4091d403d,"['science', 'education', 'tennis', 'science']",41
96,114,114,ae4eaf32-9db8-457d-ad58-1c4fad4b7eff,"['food', 'tennis', 'cooking', 'travel']",30
97,115,115,b841358a-d8ff-412e-b940-3a95fd31291b,['soccer'],26
98,116,116,1a1be722-70b0-47e0-a737-1700cffa1e6d,"['fitness', 'food', 'technology', 'studying']",32
99,117,117,4291e9a9-b4a8-42e1-b032-520b16f93888,"['travel', 'dogs', 'travel']",6

In [18]:
df.iloc[115:170,:]

,Unnamed: 0,Unnamed: 0.1,User ID,Interests,Age
115,139,139,e79a2e98-57b4-4469-8da4-87f338460d42,"['public speaking', 'science', 'culture', 'cul...",35
116,140,140,a8d09ab9-44c6-493c-afdf-93888822a4b0,"['public speaking', 'fitness']",33
117,141,141,3956593b-7739-426a-b7a5-e841c95a5df9,"['education', 'dogs']",8
118,142,142,49f49bcf-17fe-4edd-990d-16c3d1df931b,"['public speaking', 'veganism']",39
119,143,143,95f4bf3f-7eb7-429a-9f48-0f7cbdf0beaa,"['culture', 'soccer', 'culture']",38
120,144,144,568e7c6f-b1e9-4a85-897c-aaaaa0ce8832,"['cooking', 'education', 'food', 'travel']",14
121,145,145,4dc7482d-e44b-47cc-bc27-7bf663497997,"['travel', 'veganism', 'food', 'cooking']",26
122,146,146,85eca06e-b8db-4fd9-b083-da47572c40b2,"['food', 'studying']",11
123,147,147,d71363d5-6468-44b0-b641-94c4776bce98,"['tennis', 'science', 'soccer', 'culture']",20
124,148,148,1ebc46fa-edd3-4dec-bb45-c124daf83512,"['soccer', 'culture', 'animals', 'soccer']",28
125,150,150,9bb5d084-0b28-4352-8591-5b5a4efecdf0,"['tennis', 'fitness', 'healthy eating', 'anima...",19
126,151,151,dbacabf8-7ebd-4f22-a261-59d8dad306f1,"['tennis', 'culture', 'technology', 'science']",6
127,152,152,7a85fbc6-253f-4552-9f4a-c1a332e14fa5,['studying'],26
128,153,153,9a5aca53-6263-485a-bf77-e60c4608fd26,"['science', 'public speaking', 'animals']",31
129,154,154,0c9ea4da-c609-4b08-ab44-1da0530ba364,"['soccer', 'public speaking']",28
130,155,155,1f81cb56-5258-4f9e-ab2c-4dfb581b44cb,['cooking'],22
131,156,156,311d7214-711f-4f66-bc9a-e835fa54ffb6,"['dogs', 'studying']",10
132,157,157,109782f9-4141-4d5a-826f-9a4ea672f65b,"['fitness', 'animals', 'cooking', 'dogs']",9
133,158,158,fe1c151b-1a95-43fa-9a4c-f3214adba852,['soccer'],39
134,159,159,c76c3393-88e2-47b0-ac37-dc4f2053f5a5,"['culture', 'healthy eating', 'studying', 'soc...",8
135,160,160,49da0743-cb4d-4c84-b6a2-537bbe7256d1,"['soccer', 'travel']",41
136,161,161,acd90ee9-84cd-465e-88e3-f128dd0cc1da,['culture'],37
137,162,162,f02267ef-8974-43f5-9a2f-03d2c8ec22ca,"['animals', 'cooking', 'food', 'food']",42
138,163,163,b0d6f088-ee97-4087-aeb1-4957f24a5f4d,['veganism'],25
139,164,164,6978b891-dea2-4217-8bc8-47d5aa25e743,"['animals', 'animals', 'food']",33
140,165,165,c880dbc5-8997-4f38-9055-c254b9133175,"['education', 'culture', 'public speaking']",18
141,166,166,33a8d02a-e255-4ffe-9d90-2df8c2914077,"['dogs', 'public speaking', 'studying', 'food']",37
142,167,167,c64c5004-6ab5-4faa-9fcd-8039fe57799d,"['healthy eating', 'technology', 'science', 'e...",16
143,168,168,2c32ac39-926d-4473-801f-5733222ad74f,"['science', 'fitness', 'cooking']",10
144,169,169,06a8036a-6e4c-4b15-a6c8-ca74ac11ea73,['soccer'],6
145,172,172,289044c8-e74c-4814-898a-b3b5eba6e46e,"['veganism', 'tennis', 'cooking']",10
146,173,173,a6668254-c779-424c-8c8b-1762bf45916e,"['food', 'dogs', 'studying']",35
147,174,174,cd5fd7db-8715-41b7-8f4a-11a65b638d8e,"['science', 'education', 'veganism']",9
148,176,176,a58444bc-a23e-40a1-b09d-0f90bd5cd6b3,"['culture', 'education']",21
149,177,177,808f5b0d-17e3-44e1-b58e-7f35ebabaff2,"['tennis', 'cooking', 'fitness', 'food']",24
150,178,178,3663e3e6-3d5c-4ed9-a6af-1e680ec5f34b,"['soccer', 'travel']",14
151,179,179,68724f58-bc4d-4ab0-a4e1-60cdd5e95e7d,"['public speaking', 'cooking', 'science']",33
152,181,181,987b33de-7307-48c1-b34a-6c6806d7af67,"['soccer', 'science']",39
153,183,183,85503a94-e733-486e-989e-12ff9b59f2d3,['animals'],38
154,184,184,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,"['education', 'studying']",13
155,185,185,4ce3f877-96ea-4a37-8107-1176126d9d97,"['soccer', 'dogs', 'public speaking']",40
156,187,187,37867a23-d07b-4990-8fa8-d694cf7d3b1b,"['soccer', 'cooking', 'cooking', 'healthy eati...",34
157,188,188,425b7021-0409-4358-af39-2bff14197d0a,['travel'],20
158,189,189,7719b807-bf22-4b36-8f69-44d9a87d239b,"['dogs', 'fitness']",20
159,190,190,e377a5c2-0378-4684-b7d1-5d80e04243ed,"['studying', 'public speaking', 'animals', 'ed...",41
160,193,193,a6f003be-b0fd-4100-b4cc-f568a21b9745,"['public speaking', 'healthy eating', 'healthy...",36
161,194,194,87026ce7-fd0b-4b57-9126-d4bae2c1ee0e,"['travel', 'public speaking', 'animals', 'scie...",18
162,195,195,1ee25417-3648-4220-9b8f-fc82d1ef450c,['travel'],32
163,196,196,23483ddd-e43e-4c5f-a1b7-5392410aa8d1,['studying'],26
164,197,197,c07fd88f-9e7b-47eb-8477-8fcbffb7c5c8,"['healthy eating', 'veganism']",11
165,198,198,e57c1d53-11ce-4df6-bb4b-85647776fd6d,"['travel', 'studying']",25
166,199,199,624db443-c716-4227-ac84-a6f7c3a59162,"['education', 'culture']",17
167,200,200,4baf648a-0ad5-412d-8250-5a0ff9289fbf,"['travel', 'healthy eating']",41
168,201,201,ab9a4d70-3ae4-48d6-b161-c18bd687c3b4,"['fitness', 'fitness', 'veganism']",25
169,202,202,caa8605b-5cd3-49d0-a680-2a6e9f3bf0a5,['veganism'],38

In [19]:
df.iloc[190:250,:]

,Unnamed: 0,Unnamed: 0.1,User ID,Interests,Age
190,227,227,b1ceae0c-016d-421f-a6f0-488a7857f9f6,"['culture', 'education']",9
191,228,228,24789387-968b-425a-8836-14e243cda16c,"['animals', 'food', 'healthy eating']",14
192,230,230,ed3494e3-695b-4068-a725-09c6cdf92d63,"['public speaking', 'healthy eating', 'technol...",43
193,231,231,afab7336-04d3-45fe-8917-0327c56e7435,"['travel', 'cooking']",11
194,232,232,89d6bd9d-ce6b-42e5-bb9b-ece3b338396d,"['veganism', 'education', 'soccer']",15
195,233,233,948f7e9d-49bb-4770-bc9d-cb3fb65cca15,"['soccer', 'studying', 'soccer']",11
196,234,234,15e325b1-c221-4bf8-8010-18d76b03646e,"['tennis', 'studying']",10
197,235,235,3954373b-2411-4d3a-98ba-03bafc1a1a6d,"['technology', 'public speaking', 'cooking']",13
198,236,236,b3e73328-3638-4913-b7ae-3a6a64c1cd62,"['education', 'culture', 'healthy eating']",25
199,237,237,47def058-01cc-478f-9830-eaddcccac633,"['fitness', 'veganism', 'dogs', 'fitness']",22
200,238,238,6fb7ead6-71f3-4f57-94bd-18111fbc5e1a,"['education', 'science', 'science', 'education']",41
201,239,239,30be2156-59d1-451e-beea-1a3690200a2b,"['healthy eating', 'fitness', 'tennis']",15
202,242,242,b6fd2140-f8b9-498a-a07f-0dc9986736c6,"['soccer', 'fitness', 'public speaking', 'educ...",40
203,243,243,73a9e869-62a6-4508-b146-20dc9de19276,['public speaking'],7
204,244,244,8d67b1c4-cd76-4701-a908-738e7a2411e7,"['public speaking', 'science', 'food', 'vegani...",18
205,245,245,13c06e7e-833d-47eb-a790-5e09ccfd8d2c,"['tennis', 'animals']",28
206,246,246,7e263bf1-e036-4cc8-9cb8-9beec89027a3,"['food', 'tennis', 'animals']",38
207,247,247,122c3e03-0a96-4d62-9d17-27f8e2b6ba58,['public speaking'],39
208,248,248,6053d7e5-47da-4156-8b7c-dacf23a0e660,"['soccer', 'food', 'healthy eating', 'travel']",31
209,250,250,9a84c667-c913-47ce-be69-0f847dbfe0db,['soccer'],37
210,251,251,80e03bc0-fc8f-475b-a4dd-870844b7a313,"['science', 'education']",20
211,252,252,192a526b-4952-4bda-b659-4661dab12716,"['healthy eating', 'healthy eating']",34
212,253,253,1545ddaf-2b75-4143-82fe-b88966aee4fb,"['culture', 'veganism']",17
213,254,254,63e1cb43-d3dc-491a-af16-209c1c152c44,"['dogs', 'technology']",19
214,255,255,1bcc3c26-e82e-40f4-9d16-3311c8c1ddf6,"['travel', 'studying']",10
215,256,256,286516cf-d236-40de-8d28-7d0bd173125d,"['animals', 'education', 'tennis']",39
216,257,257,b827588c-31b2-47f3-916a-a1dbf7987f50,"['soccer', 'food', 'soccer']",30
217,259,259,b09e3125-2162-443b-bea0-25895b7605bc,['technology'],42
218,261,261,3455a646-398f-4b16-b19a-1371cdb2e048,['veganism'],39
219,262,262,80fc5e28-17ac-4e79-b9df-0d500abbe8b5,"['healthy eating', 'cooking', 'culture']",43
220,263,263,bc142f57-1307-46c6-9975-8c3a1e5f540c,"['education', 'tennis']",19
221,264,264,c834ba1d-8a10-4984-aaf2-7c2eab207076,"['veganism', 'dogs', 'dogs', 'food']",24
222,265,265,242a3620-fc18-4120-ac72-37b0f3716879,"['public speaking', 'healthy eating']",33
223,266,266,740a4abd-187d-4783-990b-161c52fb5f86,"['fitness', 'animals']",35
224,268,268,a4a3247c-5e68-49d0-a768-a8d7db1c8ef4,"['travel', 'tennis', 'tennis', 'culture']",24
225,269,269,de39bbda-66a8-4c52-835a-7a104cf7f081,"['public speaking', 'travel', 'education']",34
226,270,270,19fa2bc2-96ab-45b6-99de-1995c2bee330,"['veganism', 'science']",8
227,271,271,4eed2f45-f040-4995-a60f-472af1ff379a,['soccer'],9
228,272,272,4ef2c812-b152-4a72-a443-f4ff787d7b0d,"['public speaking', 'culture', 'technology']",6
229,273,273,7adafb3c-7c7c-492b-be5b-5ddd9ff1316a,"['public speaking', 'studying', 'public speaki...",16
230,275,275,7d8464e7-44df-46bd-b338-d599eb730ea2,['public speaking'],19
231,276,276,c3988ef2-7e28-4db7-8981-c69f61a3bfce,"['fitness', 'cooking', 'science']",16
232,277,277,f50ac030-3af8-4e07-aacf-dccff353b8f6,['education'],23
233,278,278,76a034b7-e163-4735-a15b-b0ff645ca627,"['fitness', 'education', 'culture', 'soccer']",31
234,279,279,d1a89d23-7d17-4949-9e1a-637317141f3d,"['studying', 'public speaking']",14
235,281,281,18421d97-6f86-4d21-a7b1-dcc57dd8be76,"['dogs', 'education', 'culture', 'veganism']",15
236,284,284,72d2587e-8fae-4626-a73d-352e6465ba0f,"['soccer', 'culture']",21
237,285,285,ef629f00-391d-4a79-af74-77a9afdbbd41,"['food', 'public speaking', 'public speaking',...",42
238,286,286,9a5c1dcc-d26b-4303-b487-3075e7d34e02,"['public speaking', 'education', 'veganism', '...",39
239,287,287,05d7e77f-a18a-4358-a23a-46c560b3682e,"['veganism', 'veganism', 'veganism']",8
240,288,288,acbac577-54c9-4476-af3c-a3241a3f4a19,['food'],13
241,289,289,45064aca-5e28-4b1f-be64-202fc5e0daba,"['public speaking', 'dogs', 'cooking']",35
242,290,290,31cfc138-cec0-4176-bd6d-79c4cadbb1d4,"['public speaking', 'travel', 'animals']",27
243,291,291,3d5f257e-556b-4e19-b127-977bc5c4daed,"['studying', 'technology', 'soccer']",25
244,292,292,f9775602-43ab-4d54-ad93-7c9a489879bc,"['animals', 'public speaking', 'veganism']",40
245,293,293,af647535-dae8-4ca3-9203-bf4bfc607ffe,"['tennis', 'technology', 'healthy eating', 'ed...",16
246,294,294,9e9cf8e7-6731-47da-bc0f-3a487e835586,"['tennis', 'science', 'technology']",43
247,295,295,6f2e20b4-5d7f-4345-b5a1-71a768ab8050,['science'],7
248,296,296,fe224147-e893-4178-b46e-b12f22bd7ed1,"['tennis', 'travel', 'technology', 'tennis']",12
249,297,297,683d880b-3ccf-4f4d-8182-96e7a7a884bd,"['culture', 'tennis', 'veganism', 'fitness']",27

In [20]:
df.iloc[293:350,:]

,Unnamed: 0,Unnamed: 0.1,User ID,Interests,Age
293,348,348,bf721d00-4fa1-44b1-834f-4730cd51aefa,"['fitness', 'public speaking', 'culture', 'sci...",38
294,349,349,f0ef81ec-85b1-4475-ae60-aa7d373088aa,"['tennis', 'soccer', 'animals', 'tennis']",36
295,350,350,9b8a3e97-eee6-4de5-ab88-e00d2c0db6b9,"['dogs', 'soccer']",6
296,351,351,61d88e0e-c0e7-4352-85ad-555e464ff933,"['soccer', 'science']",27
297,352,352,2ad548cd-a899-4992-972b-92cde9cea8f1,"['travel', 'soccer', 'public speaking', 'scien...",27
298,353,353,ffdb3615-516c-422f-aa24-a137e3027d3a,"['food', 'technology', 'cooking']",35
299,354,354,31ff6616-c1dc-4b9a-8091-0b4d0cac25b1,['science'],15
300,356,356,941db1b1-270d-47f8-8a96-43f5a7481f03,"['healthy eating', 'science', 'public speaking...",14
301,357,357,e8849148-1482-4926-9f28-a537630b9ba2,"['dogs', 'public speaking', 'fitness']",15
302,358,358,b7e4b060-7b74-408f-b7d7-67a5e1dbfce3,"['food', 'fitness', 'dogs']",44
303,359,359,5870e611-6218-48e1-a9a0-ba86fe5598f7,['public speaking'],19
304,361,361,f73a01fe-444d-4b94-8d0e-4ec2cb97495b,"['food', 'science', 'animals']",27
305,362,362,56e65b5b-e1b4-4f67-b596-e75bf103783b,"['healthy eating', 'culture', 'fitness']",35
306,363,363,4027aa31-4bda-4e1d-92f7-49de962e8da9,['animals'],23
307,364,364,2546684f-0387-4c46-b19b-9a5ddb2ef221,"['travel', 'fitness', 'healthy eating', 'publi...",7
308,365,365,93dd80c0-4ff2-42ed-9949-1621b0a68c63,"['culture', 'fitness', 'food', 'veganism']",42
309,366,366,4bc62825-3109-4796-9465-1bf853165347,"['technology', 'food', 'dogs', 'soccer']",43
310,367,367,ef147ea5-9696-44d5-b6c2-a43f62fd8ce2,"['studying', 'soccer']",42
311,368,368,f5d9a26e-986d-4d8e-a1c9-69493fb64736,"['culture', 'cooking', 'technology', 'travel']",36
312,369,369,a540d720-b44a-4d3d-9643-e12bca77d1f3,"['soccer', 'travel']",15
313,370,370,ce7c338c-cad4-408f-895b-510ca73a388b,"['travel', 'food', 'culture']",22
314,372,372,38cceae3-14e0-49bb-8087-f6f210a2053a,"['veganism', 'technology']",39
315,373,373,ddc4db8e-0000-48c4-8fdb-d32af87fb823,"['tennis', 'food', 'dogs']",16
316,374,374,7f8ef27a-73f4-4bc1-aa62-f8aaea817294,"['soccer', 'studying', 'food', 'tennis']",16
317,375,375,db392b86-6ba5-4a9b-933a-a2553488bb62,"['healthy eating', 'culture']",10
318,376,376,66663a0d-856f-487f-a2a2-258af21ab3e5,"['healthy eating', 'science', 'public speaking']",21
319,377,377,3f218ab6-a288-4ee8-affc-3d02a9cbff5f,['food'],29
320,379,379,e69d9ade-20e5-4e31-bc70-5a46556c530f,"['dogs', 'food']",16
321,380,380,f8926cfa-7036-4929-b5db-925c26daea1a,"['education', 'soccer', 'travel', 'dogs']",31
322,382,382,54729154-eb5c-413a-8837-887365057910,['science'],14
323,383,383,d3aa94aa-3e81-49e4-915a-d269e4f42f29,"['science', 'dogs', 'tennis', 'science']",38
324,384,384,a4fd7920-9edf-4930-84bd-7a38b3bf9cec,"['food', 'fitness']",39
325,385,385,e2377b94-f06a-49ed-a266-377c4b07e980,"['dogs', 'cooking', 'fitness']",28
326,386,386,beb1f34e-7870-46d6-9fc7-2e12eb83ce43,"['food', 'cooking', 'technology', 'science']",13
327,387,387,5b62e10e-3c19-4d28-a57c-e9bdc3d6758d,['tennis'],24
328,388,388,89572273-761e-46f3-8b99-1689d98aac90,"['dogs', 'public speaking', 'animals', 'soccer']",9
329,389,389,6178d76a-af2e-4453-93ee-02ca23ed3fdc,"['cooking', 'cooking', 'cooking']",29
330,390,390,b3a84639-5a4f-4c97-8ea8-2ac49882e27a,['fitness'],10
331,391,391,274ac4ac-395a-4f70-90e5-9771ac3db11b,"['food', 'travel']",32
332,392,392,de1d478e-3552-4223-b039-d3086cc485ec,"['cooking', 'education']",17
333,393,393,10f311c3-f547-4260-8c0e-a155008b7936,"['cooking', 'healthy eating', 'soccer']",18
334,394,394,b0c22f82-b882-4394-bf27-6dfadf26e5c2,['studying'],11
335,395,395,8abcf667-7be3-439f-97bb-3375a3de366c,['education'],41
336,396,396,3d13e0d3-e765-4065-9221-3f864689b9e0,"['dogs', 'education', 'dogs']",8
337,397,397,b473e898-b7b0-4a57-959d-484bf4cc4483,"['food', 'soccer']",44
338,398,398,a94a7d87-65df-4c21-847a-0e8af6cb5c02,"['dogs', 'culture']",31
339,399,399,6eb62858-f6f3-4846-8054-52df483979de,"['animals', 'public speaking']",31
340,400,400,fc709c94-7491-4753-ad53-dfee49823a2f,"['soccer', 'healthy eating', 'veganism']",28
341,401,401,9fbae7e6-65a9-4753-8db9-5f7855b6a540,"['soccer', 'animals', 'soccer']",23
342,402,402,b596e7d8-dd3f-4125-8b99-4bf2283657cd,['cooking'],38
343,403,403,58fc0c8b-f669-4ee3-9a92-6d4290d85277,"['education', 'fitness', 'dogs', 'healthy eati...",12
344,405,405,104c4dcb-70d5-4d87-b5b5-8b67205891fe,"['fitness', 'culture', 'cooking', 'studying']",7
345,406,406,c8145b49-3841-466e-9d49-a636ce2e7d1f,"['food', 'technology', 'food', 'education']",7
346,407,407,bb987a93-cd4f-4b6b-8691-0997ff8a8ce8,"['dogs', 'science', 'animals', 'studying']",37
347,408,408,2ef20e99-8be8-4ab6-a817-83991f7a0fa3,"['food', 'veganism', 'soccer', 'travel']",7
348,409,409,34fcadd6-fa9b-4404-981a-c70c86cde556,['healthy eating'],36
349,411,411,41cd692a-be3c-4acd-a2c8-184586bdc180,"['education', 'tennis', 'food']",42

In [21]:
df.iloc[405:431,:]

,Unnamed: 0,Unnamed: 0.1,User ID,Interests,Age
405,475,475,23cc47ff-e5cd-4915-828d-258aefce5a14,"['soccer', 'animals', 'healthy eating']",23
406,476,476,5d04455b-a95e-40d8-bcd4-8c485777c47f,['travel'],29
407,477,477,d56c9d87-7d56-4a5e-a0e8-bbc4ddc3242c,['science'],28
408,478,478,2dd186bb-7a28-4e80-99c7-f1936afc7b49,"['cooking', 'science', 'studying', 'culture']",16
409,479,479,317c70d5-fe65-4663-afb1-150108e0e55c,['animals'],26
410,481,481,953cb190-5704-4926-adc2-057c6f3e3cb4,['animals'],9
411,483,483,1d8dfb6a-330c-4eb9-a603-364f207c6e57,"['food', 'food']",16
412,485,485,054b5d2a-7ee3-49c8-912a-1cf58389ae60,"['studying', 'healthy eating', 'fitness', 'cul...",36
413,487,487,04e52602-e370-4a99-bfda-f0c1655058da,"['culture', 'animals', 'food']",6
414,488,488,fdbaec82-bc98-47b8-8fe6-4aec7524e8e3,"['tennis', 'healthy eating', 'food']",35
415,489,489,84bd5adb-286c-429a-926d-4ea120270825,"['veganism', 'science']",6
416,490,490,b7fb2028-4cfc-440b-a1b1-4101f12f7abe,"['animals', 'science']",9
417,491,491,07061727-dc05-4411-ab78-79f95b1869a9,['dogs'],38
418,492,492,5b3b843e-7c66-4eac-82b6-8d6f7a19277c,"['technology', 'fitness']",33
419,493,493,d0ea9a00-4ea9-4c81-b16a-a20b72f824ea,['fitness'],15
420,494,494,7246fed1-8725-4dbb-bccd-5451346f122d,"['food', 'healthy eating']",19
421,495,495,1f7e22c8-558a-4b6f-a04f-b219593f029e,"['tennis', 'veganism', 'education', 'soccer']",21
422,497,497,db0066e1-83cc-43f3-990b-983010aa5370,['soccer'],14
423,498,498,d6204684-926d-41db-ae9c-a7bf2e76313a,"['public speaking', 'dogs']",24
424,499,499,07f4dcd0-2bf3-4f21-9da3-b054b511ae00,"['education', 'science', 'animals', 'public sp...",24

In [22]:
df.drop([0,60,180,240,360,480],axis=0,inplace=True)

KeyError: '[480] not found in axis'

In [23]:
df

,Unnamed: 0,Unnamed: 0.1,User ID,Interests,Age
0,1,1,95258c36-5b6b-4591-85ee-0c43f503c1d5,['tennis'],23
1,2,2,a8229d24-f219-4930-a382-24049a8f73bb,"['fitness', 'cooking', 'animals', 'travel']",25
2,4,4,3af8d78b-55c4-4ac0-8161-7cc3f6ec11c9,['education'],44
3,5,5,2bd9c167-e06c-47c1-a978-3403d6724606,"['culture', 'healthy eating']",28
4,8,8,22056f9e-4654-44e9-930d-2fabdeb80f95,"['public speaking', 'science', 'veganism', 'te...",23
...,...,...,...,...,...
420,494,494,7246fed1-8725-4dbb-bccd-5451346f122d,"['food', 'healthy eating']",19
421,495,495,1f7e22c8-558a-4b6f-a04f-b219593f029e,"['tennis', 'veganism', 'education', 'soccer']",21
422,497,497,db0066e1-83cc-43f3-990b-983010aa5370,['soccer'],14
423,498,498,d6204684-926d-41db-ae9c-a7bf2e76313a,"['public speaking', 'dogs']",24
424,499,499,07f4dcd0-2bf3-4f21-9da3-b054b511ae00,"['education', 'science', 'animals', 'public sp...",24

In [24]:
df.to_csv("Profile (1).csv")

In [25]:
df.to_csv("Profile (1).csv", index=False)